function lookbackdb
  mongo $LOOKBACK_PRODUCTION_URL -u $LOOKBACK_PRODUCTION_USER -p $LOOKBACK_PRODUCTION_PASSWORD
end

function lookbackdbtesting
  mongo $LOOKBACK_TESTING_URL -u $LOOKBACK_TESTING_USER -p $LOOKBACK_TESTING_PASSWORD
end
